### ISSUE TITLE
Noised character at U+8D74 (赴)?

### ISSUE THREAD

**Issue by whc2001** [LingDong-/qiji-font#13]
Is that normal?

![批注 2020-02-27 223643](https://user-images.githubusercontent.com/16266909/75508572-9eb60080-59b2-11ea-8097-58b3b133d4f2.png)
![批注 2020-02-27 223632](https://user-images.githubusercontent.com/16266909/75508576-a1b0f100-59b2-11ea-83bd-49db209493e7.png)

**Comment by LingDong-** [comment]
The noise comes from the original page, which got dirty :P

![image](https://user-images.githubusercontent.com/7929704/75513787-d5484700-59c3-11ea-971a-8bedef986b66.png)

Fortunately, It seems that there is an alternative 赴 in the other book source I was using. So I will try to fix it by using the other one. Thanks a lot for pointing this out!

**Comment by whc2001** [comment]
Thanks!
