### ISSUE TITLE
Glyph error: U+5B87 (宇)

### ISSUE THREAD

**Issue by sgalal** [LingDong-/qiji-font#15]
I am using qiji-combo.ttf v0.0.1. The glyph U+5B87 (宇) looks like U+5B57 (字).

![Demo](https://user-images.githubusercontent.com/32255369/77392287-89779a80-6dd5-11ea-957e-8f67c13203ec.png)

The first row is QIJIC, while the second row is Source Han Serif K.

Steps to reproduce:

```html
<!DOCTYPE html>
<html lang="zh-Hant" dir="ltr">
<head>
<title>Test Page</title>
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
<style>
p {
  font-size: 64pt;
  margin: 0;
}
span {
  display: inline-block;
  text-align: center;
  min-width: 100px;
}
p:first-child {
  font-family: QIJIC;
}
p:first-child > span:first-child {
  font-size: 80pt;
  transform: translateX(-8px);
}
p:first-child > span:last-child {
  font-size: 88pt;
  transform: translateX(-10px) translateY(6px);
}
p:last-child {
  font-family: Source Han Serif K;
  font-language-override: "KOR";
}
</style>
</head>
<body>
<p><span>宇</span><span>字</span></p>
<p><span>宇</span><span>字</span></p>
</body>
</html>
```

The correct glyph should be as that in _Guangyun_ _Zecuntang_ Version (<span lang="zh-Hant">廣韻澤存堂本</span>, <span lang="zh-Latn">Kuangxyonh Drakzuondang puonx</span>):

![Cio](https://user-images.githubusercontent.com/32255369/77392905-efb0ed00-6dd6-11ea-9d74-733bf34e50de.png)

**Comment by LingDong-** [comment]
Indeed, this is an OCR error. I'll fix it and update here. Thanks for spotting the error!

**Comment by LingDong-** [comment]
Hi @sgalal,

Time flies! Now fixed in the new release: https://github.com/LingDong-/qiji-font/releases/tag/v0.0.2

![image](https://user-images.githubusercontent.com/7929704/89720964-e4d1b000-d9a5-11ea-9f91-64c87c9b0a17.png)

Thanks!
