### ISSUE TITLE
Some ideas

### ISSUE THREAD

**Issue by antfu** [LingDong-/qiji-font#2]
Wow! I didn't expect to see it get such a high level of completeness and I am very surprised how wide range it already covered. Great job! 👍

I haven't got the build tools ready and run by myself (I am having poor network recently, will definitely try later). Here are some quick thoughts/ideas about this with my superficial view.

1. Maybe it's better to attach the compiled font file to releases instead of source control. I think it's indeed easier and straightforward for people to find the font on early-stage, but since the Chinese font is huge (14MB currently). It's not very ideal to keep it in the source control.
![image](https://user-images.githubusercontent.com/11247099/73592897-30f4f100-453a-11ea-9369-8220932df25d.png)

2. The font name is not specified. (`Untitled1` currently)

3. Consider compile to different font formats (ttf, otf, woff, woff2, etc) by using [fontmake](https://github.com/googlefonts/fontmake). woff is optimized for the web with smaller file sizes which is useful for web display. Here is the [build script of FiraCode](https://github.com/tonsky/FiraCode/blob/cf377496bfbabf088c565e695865b3d28b2d35fc/script/build#L37-L41) for reference.

The characters selecting things look very interesting too! Would play with it and make some feedback when I finished the toolings.

**Comment by antfu** [comment]
> attach the compiled font file to releases instead of source control

As I am trying clone it to my local machine, it now takes about 88MB to download.(and sry I have really poor network right not, ~250kb/s 😂). It's not a big deal right now, but I think it's better to do it earlier.

If you are ok with it, I can peel off the QIJI.ttf from the git history and make a script that make Github release automaticly. The `site/qiji.ttf` and be automaticly copied as well.

**Comment by LingDong-** [comment]
That would be great, thanks a lot!

However the font is generated from SVG's (50MB), which are generated from BMP's(1GB), which are generated from high-res scans (15GB). Wondering if it is still possible to have Github release automatically? Otherwise I guess manual isn't too bad.

The large size is also likely because at one point I accidentally pushed a fallback font (called QIJIFALLBACK.ttf, which is 55MB) to the repo, so if you can peel that off too that would be awesome. BTW, I'm generating the fallback font by adding distortion and noise to a regular font (SourceHan), still experimenting with that.

![image](https://user-images.githubusercontent.com/7929704/74009307-e9fb6700-4950-11ea-9250-15b68638e7ee.png)

In image above, 嗑睽祐斲 are from the fallback font. Perhaps they can be slightly thicker and bigger, but I think they blend in kinda well :)

**Comment by antfu** [comment]
> the font is generated from SVG's (50MB), which are generated from BMP's(1GB), which are generated from high-res scans (15GB). 

That was crazy 😂 Hope I got enough disk space for that.

> Wondering if it is still possible to have Github release automatically?

Definitely NO haha. But what I mean is something like `bash publish.sh` that create Github Release and uploads font files to it automatilcly (or semi-auto XD) to make life a litter easier. What do you think?

> In image above, 嗑睽祐斲 are from the fallback font.

It's hard to identify which are fallback without telling. Good job. The dimension is kinda wired (look more rectanglar than square). but I believe you already spot that too.

BTW, I am working on the site for this to see if I can make the font loading experience better, will make PR later :)

**Comment by antfu** [comment]
I used fontforge to convert ttf to woff2, I was really surprised about how much the size reduced (14MB -> 4.8MB) and maybe it can be optimized even more from the source.

![S-20200207-16,04-001](https://user-images.githubusercontent.com/11247099/74012129-7b57f100-49c4-11ea-87ba-e04027090ff1.png)

**Comment by LingDong-** [comment]
> bash publish.sh

Sounds great!

> look more rectanglar than square

The real font is actually also taller than they are wide, but I guess I overdid it, will dial back a little.

> make the font loading experience better

Thanks for the PR!

> 14MB -> 4.8MB

Amazing :D

**Comment by LingDong-** [comment]
@antfu , how did you manage to get woff2 so small? 'cause this is what I'm getting XD:

![image](https://user-images.githubusercontent.com/7929704/74081032-5d1be080-4a18-11ea-9e05-ded2f1f7e397.png)

My code:

```python
import fontforge
font = fontforge.open("../qiji.ttf")
font.generate("../qiji.woff2")
```

**Comment by antfu** [comment]
@LingDong- I am using the FontForge GUI, I just simpliy open the ttf file and output as woff2. That's it. Not sure how to work with python, maybe there are some options for compressing or optimizing?

**Comment by antfu** [comment]
> peel off the QIJI.ttf from the git history

This will rewrite the git history, so I want to make sure you have your unsaved works committed and pushed. Let me know when you are ok with it, after I finished(it would not take long), I will share you some simple commands to pull the changes. :)

**Comment by LingDong-** [comment]
I've made a backup, feel free to do the git surgery, thanks :)

**Comment by antfu** [comment]
@LingDong- The process is finished :) You can either reclone it or run the following command to pull
```
git fetch --all
git reset --hard origin/master
git pull origin master
```

I have removed `QIJI.ttf`, `qiji-fallback.ttf`, `site`, `__pycache__` from the history

**Comment by LingDong-** [comment]
Cool, I ran the commands and it seems to be working fine. Thanks a lot for doing this!

**Comment by antfu** [comment]
>  I am using the FontForge GUI

Tried out some online converters, found out the similar result
https://cloudconvert.com/ttf-to-woff2

|Source: [Qiji.ttf](https://github.com/LingDong-/qiji-font/releases/download/v0.0.1/qiji.ttf)| 14.1MB |
|-|-|
|woff| 7.32MB|
|woff2| 4.78MB|
|otf| 50MB (wtf?)|

If we can not make fontforge optimize it, maybe we can use some other font tools to do the convertion in sh scripts? (have to say docs for fontfoge python is really... not too friendly)

**Comment by LingDong-** [comment]
Yeah FontForge python's documentation is non-existent XD. I basically go `dir(fontforge)` and then `dir(fontforge.font())` to see what it has to offer... 

https://fontforge.org/en-US/documentation/scripting/python/ here is an inaccurate and outdated doc which I also use as reference.

I'm switching to this tool for conversion:

https://www.npmjs.com/package/ttf2woff2

Commit: af5a229ad30f8a7b57e8b7b170f97ae36594206f

Result: QIJI.woff2 is 5.2MB, so I guess that's acceptable(?)

ttf2woff2 has a CLI, wondering if installing it globally and use it in a shell script is better, thus avoiding cluttering package.json.

**Comment by antfu** [comment]
Oh, I didn't expect the solution to be that simple - just a js package!

I guess 5.2MB is already a big optimization compare to 14.1MB for now. We can try to find ways to squeeze its size (maybe gzip or svg optimizing), but I think let's for later.

> if installing it globally and use it in a shell script is better

I was trying to say maybe `npx ttf2woff2` but I just quick peeked its document, not sure if npx works with bash pipeline (it does not support argv parsing)


Can you upload the woff2s to the release(no need to create a new one I think) so that I can help to switch to woff2 for site?

**Comment by LingDong-** [comment]
I added `qiji.woff2` to the release. `qiji-combo.woff2` is taking forever to generate, not sure why. Every tool has to break in its particular fashion 🤦‍♂️

**Comment by lapomme** [comment]
For most characters, the Korean version of Source Han Serif would be more suitable for the fallback since it uses 舊字形.  Also, I think [GenWan](https://github.com/ButTaiwan/genwan-font) would work nicely.
E.g. 祐: from left to right, Source Han Serif SC, Source Han Serif K, GenWan.
![image](https://user-images.githubusercontent.com/27000939/74560328-56b7c800-4f34-11ea-8afb-1c5f23f4fb85.png)

**Comment by LingDong-** [comment]
@lapomme , Good call, Thanks a lot!

Now the fallback font and the combined font are generated with the Korean version `SouceHanSerifK-SemiBold`, and are published on the Releases page.

P.S. GenWan looks nice, but I think since we're adding a lot more distortion & weight variations to the glyphs, the subtle variation from GenWan might not be very visible. But nevertheless I might give it a try later.
