### ISSUE TITLE
Font family

### ISSUE THREAD

**Issue by antfu** [LingDong-/qiji-font#7]
https://github.com/LingDong-/qiji-font/blob/f2964e5cbe4df7f820e7a491c064b77c86d32be6/fallback/forge_font.py#L14-L16

https://github.com/LingDong-/qiji-font/blob/f2964e5cbe4df7f820e7a491c064b77c86d32be6/fallback/forge_combined.py#L14-L16

https://github.com/LingDong-/qiji-font/blob/f2964e5cbe4df7f820e7a491c064b77c86d32be6/workflow/forge_font.py#L17-L19

Should we share them with a common family name while they have different font names and full names? It's something like `Helvetica Bold`, `Helvetica Narrow`, `Helvetica Conth` etc. Users can select the font first then select the variations in GUIs.

**Comment by LingDong-** [comment]
Hmm I don't know, I think the three are functionally different things, they're not like variations of the same font. 

In the future when we have bold and light versions of the font, then we can put them under the same family name.

I'm thinking one way to make the bold and light faces is perhaps to bias the threshold operation while generating the rasters. Or erode/dilate them afterwards. It's not the "proper" way to do it, but I guess no harm in trying out and see :)

**Comment by antfu** [comment]
Yeah I think you are right :)
